packages:
  - apps/*
  - packages/*
  - tooling/*

catalogs:
  dev:
    "@tailwindcss/vite": ^4.1.14
    "@testing-library/jest-dom": ^6.9.1
    "@types/chrome": ^0.1.22
    "@vitejs/plugin-react": ^5.0.4
    "typescript-eslint": ^8.45.0
    '@babel/core': ^7.28.4
    '@pixpilot/dev-config': ^3.1.1
    '@testing-library/react': ^16.3.0
    '@types/node': ^24.7.1
    '@types/react': ^19.2.0
    '@types/react-dom': ^19.2.0
    '@vitest/coverage-v8': ^3.2.4
    '@vitest/ui': ^3.2.4
    autoprefixer: ^10.4.21
    eslint: ^9.37.0
    glob: ^11.0.3
    jsdom: ^27.0.0
    postcss: ^8.5.6
    prettier-plugin-tailwindcss: ^0.6.14
    prettier: ^3.6.2
    rollup: ^4.46.2
    tailwindcss: 4.1.12
    typescript: ^5.9.3
    vite: ^7.1.9
    vitest: ^3.2.4

  prod:
    react: 19.1.1
    react-dom: 19.1.1
    zod: 4.0.17
