packages:
  - apps/*
  - packages/*
  - tooling/*

catalogs:
  dev:
    "@tailwindcss/vite": ^4.1.16
    "@testing-library/jest-dom": ^6.9.1
    "@types/chrome": ^0.1.24
    "@vitejs/plugin-react": ^5.0.4
    "typescript-eslint": ^8.46.2
    '@babel/core': ^7.28.5
    '@pixpilot/dev-config': ^3.16.0
    '@testing-library/react': ^16.3.0
    '@types/node': ^22.18.12
    '@types/react': ^19.2.2
    '@types/react-dom': ^19.2.2
    '@vitest/coverage-v8': ^4.0.2
    '@vitest/ui': ^4.0.2
    autoprefixer: ^10.4.21
    eslint: ^9.38.0
    glob: ^11.0.3
    jsdom: ^27.0.1
    postcss: ^8.5.6
    prettier-plugin-tailwindcss: ^0.7.1
    prettier: ^3.6.2
    rollup: ^4.52.5
    tailwindcss: 4.1.12
    typescript: ^5.9.3
    vite: ^7.1.12
    vitest: ^4.0.2
    tsdown: ^0.15.9

  prod:
    react: 19.1.1
    react-dom: 19.1.1
    zod: 4.0.17
